apiVersion: apps/v1
kind: Deployment
metadata:
  name: bachelor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bachelor-app
  template:
    metadata:
      labels:
        app: bachelor-app
    spec:
      containers:
        - name: bachelor-app
          image: bachelor-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              value: mydb
---
apiVersion: v1
kind: Service
metadata:
  name: bachelor-app-service
spec:
  type: NodePort
  selector:
    app: bachelor-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
